const quotes = [
  "Breathe in peace, breathe out stress.",
  "You are exactly where you need to be.",
  "Do less. Be more.",
  "Let it be soft. Let it be slow.",
  "Stillness is strength.",
  "Nothing blooms all year.",
  "You are not behind. You are not late.",
  "Be gentle with yourself today.",
  "This moment is enough.",
  "You deserve rest too.",
  "You're doing your best. That is enough.",
  "There is beauty in the quiet.",
  "No rush. Just rhythm.",
  "You are allowed to pause.",
  "Let go. Flow slow.",
  "Peace begins within.",
  "One breath at a time.",
  "Soft focus. Quiet heart.",
  "You carry light.",
  "Release. Reset. Return.",
  "You don’t have to fix everything.",
  "Clouds move. So will this.",
  "Slow is still progress.",
  "Let it be simple. Let it be kind.",
  "Even silence holds meaning.",
  "Waves come. And they pass.",
  "Calm is a superpower.",
  "Everything changes. Even this.",
  "You are more than your thoughts.",
  "Inhale love. Exhale doubt.",
  "Honor your own rhythm.",
  "Your energy is sacred.",
  "Sink into softness.",
  "You are safe in stillness.",
  "There’s no race. Only rhythm.",
  "Whispers matter too.",
  "Embrace the quiet moments.",
  "You are your own home.",
  "Slowness is strength.",
  "Exist. That’s enough.",
  "Linger in light.",
  "This breath. Then the next.",
  "Permission to rest: granted.",
  "You glow differently when at peace.",
  "Notice the small things.",
  "The moon doesn’t rush.",
  "Peace looks good on you.",
  "You're allowed to just be.",
  "Quiet doesn’t mean empty.",
  "Softness is not weakness.",
  "You’re not meant to hold it all.",
  "The pause is part of the process.",
  "Even still water reflects the stars.",
  "Let the light in slowly.",
  "You are more than the noise.",
  "Don’t shrink. Just soften.",
  "Keep floating.",
  "This is a chapter, not the whole story.",
  "Healing is not linear.",
  "Every breath is a reset.",
  "You don’t owe anyone your peace.",
  "It’s okay to be in between.",
  "Trust the quiet work.",
  "Bloom in your own season.",
  "You are whole, even in rest.",
  "Let yourself be light.",
  "Ease is not laziness.",
  "Float through, don’t force through.",
  "It’s okay to pause before continuing.",
  "Stay soft, even here.",
  "The world will wait.",
  "You can hold peace and ambition.",
  "Even stars need darkness.",
  "Your pace is perfect.",
  "Let your mind rest.",
  "Protect your peace.",
  "This breath belongs to you.",
  "Wrap yourself in calm.",
  "Rest is productive too.",
  "Exist without explanation.",
  "Your softness is divine.",
  "Let quiet be your rebellion.",
  "This is your moment to breathe.",
  "There is grace in slowing down.",
  "Unfold gently.",
  "You’re allowed to stop striving.",
  "Energy flows where calm goes.",
  "Today needs less noise.",
  "Let peace be your default.",
  "Comfort is a form of power.",
  "You don’t have to sparkle to shine.",
  "Even a whisper can be powerful.",
  "This stillness is sacred.",
  "You are doing just fine.",
  "Even clouds drift without effort.",
  "Tend to your inner garden.",
  "You are safe in softness.",
  "Stay gentle. Stay grounded.",
  "Release what’s too heavy.",
  "Glow quietly.",
  "Your rest is your revolution.",
  "You’re allowed to exhale.",
  "Move like mist. Think like light."
]

export default quotes;
